apiVersion: v1
entries:
  mariadb:
  - apiVersion: v1
    appVersion: 10.3.20
    created: "2019-11-14T00:13:25.666491-07:00"
    description: Fast, reliable, scalable, and easy to use open-source relational
      database system. MariaDB Server is intended for mission-critical, heavy-load
      production systems as well as for embedding into mass-deployed software. Highly
      available MariaDB cluster.
    digest: 7c441c88248ad7ad787cfd51cea016c1e3c19b7eb6f11a180918462c404be469
    engine: gotpl
    home: https://mariadb.org
    icon: https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png
    keywords:
    - mariadb
    - mysql
    - database
    - sql
    - prometheus
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: mariadb
    sources:
    - https://github.com/bitnami/bitnami-docker-mariadb
    - https://github.com/prometheus/mysqld_exporter
    urls:
    - http://127.0.0.1:8879/mariadb-7.0.1.tgz
    version: 7.0.1
  wordpress:
  - apiVersion: v1
    appVersion: 5.2.4
    created: "2019-11-14T00:13:25.669058-07:00"
    description: Web publishing platform for building blogs and websites.
    digest: 90eb0b414e10c89c966052e5a4b8047a570bd41ea8f437f54fcb61951ea650d2
    engine: gotpl
    home: http://www.wordpress.com/
    icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
    keywords:
    - wordpress
    - cms
    - blog
    - http
    - web
    - application
    - php
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: wordpress
    sources:
    - https://github.com/bitnami/bitnami-docker-wordpress
    urls:
    - http://127.0.0.1:8879/wordpress-8.0.0.tgz
    version: 8.0.0
generated: "2019-11-14T00:13:25.665215-07:00"
